package jkulan.software.model;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * Created by tth on 1/18/16.
 */
@Entity
@Table(name = "users")
public class User {

    // ------------------------
    // PRIVATE FIELDS
    // ------------------------

    // An autogenerated id (unique for each jkulan.software.model in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;

    // The jkulan.software.model's name
    @NotNull
    private String name;

    // The jkulan.software.model's address
    @NotNull
    private String address;

    @NotNull
    private String email;

    // ------------------------
    // PUBLIC METHODS
    // ------------------------

    public User() { }

    public User(long id) {
        this.id = id;
    }

    public User(String address, String name) {
        this.address = address;
        this.name = name;
        this.email= address;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }
}
